import { For, Show, createEffect, createResource, createSignal, onMount } from "solid-js";
import { Shell } from "../components/Shell";
import { api } from "../lib/api";
import type { CareEvent, CareStatus, CatAccount, Note, Responsibility, Session, TriageAssessment } from "../lib/contracts";

const labels: Record<string, string> = { clear: "All calm", planned: "Care planned", due_soon: "Coming up", overdue: "Needs attention", unknown: "Needs scheduling" };
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No due date yet";
const withCat = (path:string, catID:string) => `${path}${path.includes("?")?"&":"?"}cat_id=${encodeURIComponent(catID)}`;

type CatCare = { cat:CatAccount; status:CareStatus; responsibilities:Responsibility[]; timeline:CareEvent[]; notes:Note[]; triage:TriageAssessment[] };

export default function Today() {
  const [session, { refetch: refetchSession }] = createResource(() => api<Session>("session"));
  const [care, { refetch: refetchCare }] = createResource(() => session()?.cats, async cats => Promise.all(cats.map(async cat => {
    const [status,responsibilities,timeline,notes,triage] = await Promise.all([
      api<CareStatus>(withCat("status",cat.id)), api<Responsibility[]>(withCat("responsibilities",cat.id)), api<CareEvent[]>(withCat("timeline",cat.id)), api<Note[]>(withCat("notes",cat.id)), api<TriageAssessment[]>(withCat("triage",cat.id)),
    ]);
    return {cat,status,responsibilities:responsibilities??[],timeline:timeline??[],notes:notes??[],triage:triage??[]} satisfies CatCare;
  })));
  const [actionCat,setActionCat]=createSignal("");
  const [formVisible,setFormVisible]=createSignal(false); const [quickAction,setQuickAction]=createSignal<"observation"|"care"|null>(null);
  const [commentingOn,setCommentingOn]=createSignal<string|null>(null); const [commentText,setCommentText]=createSignal(""); const [comments,setComments]=createSignal<Record<string,string[]>>({});
  const [title,setTitle]=createSignal(""); const [category,setCategory]=createSignal("veterinary"); const [dueAt,setDueAt]=createSignal(""); const [recurrenceDays,setRecurrenceDays]=createSignal(0);
  const [noteText,setNoteText]=createSignal(""); const [careType,setCareType]=createSignal("measurement"); const [careDescription,setCareDescription]=createSignal("");
  const [error,setError]=createSignal(""); const [notice,setNotice]=createSignal(""); const [saving,setSaving]=createSignal(false); const [hydrated,setHydrated]=createSignal(false);
  onMount(()=>setHydrated(true));
  createEffect(()=>{if(!actionCat()&&session()?.active_cat_id)setActionCat(session()!.active_cat_id)});

  const selectedCatID=()=>actionCat()||session()?.active_cat_id||session()?.cats[0]?.id||"";
  const catName=(catID:string)=>session()?.cats.find(cat=>cat.id===catID)?.profile.name??"Cat";
  const rememberCat=async(catID:string)=>{if(catID&&catID!==session()?.active_cat_id)await api(`cats/${catID}/select`,{method:"POST"});await refetchSession()};
  const command=async(path:string,body?:unknown,catID=selectedCatID())=>{setError("");setNotice("");try{await api(withCat(path,catID),{method:"POST",body:body===undefined?undefined:JSON.stringify(body)});setActionCat(catID);await rememberCat(catID);await refetchCare()}catch(failure){setError(failure instanceof Error?failure.message:"The care command failed");throw failure}};
  async function createResponsibility(event:SubmitEvent){event.preventDefault();setSaving(true);const id=selectedCatID();try{await command("responsibilities",{title:title(),category:category(),due_at:dueAt()?new Date(dueAt()).toISOString():null,recurrence_days:recurrenceDays(),recurrence_months:0},id);setTitle("");setDueAt("");setRecurrenceDays(0);setFormVisible(false);setNotice(`Responsibility added for ${catName(id)}.`)}catch{}finally{setSaving(false)}}
  async function recordNote(event:SubmitEvent){event.preventDefault();const id=selectedCatID();try{await command("notes",{description:noteText()},id);setNoteText("");setQuickAction(null);setNotice(`Observation added to ${catName(id)}'s care history. It remains a note, not a diagnosis.`)}catch{}}
  async function recordCare(event:SubmitEvent){event.preventDefault();const id=selectedCatID();try{await command("care-events",{type:careType(),description:careDescription(),responsibility_id:""},id);setCareDescription("");setQuickAction(null);setNotice(`Care event added to ${catName(id)}'s history.`)}catch{}}
  const notify=(catID:string,id:string)=>command("notifications",{responsibility_id:id,outcome:"delivered"},catID).then(()=>setNotice("Notification delivered; responsibility state was not changed.")).catch(()=>{});
  const deferSevenDays=(catID:string,id:string,currentDue:string|null)=>command(`responsibilities/${id}/defer`,{due_at:new Date(Math.max(Date.now(),currentDue?new Date(currentDue).getTime():0)+7*86400000).toISOString()},catID).then(()=>setNotice("Responsibility deferred by seven days.")).catch(()=>{});
  const requestTriage=(catID:string,noteID:string)=>command("triage",{note_ids:[noteID]},catID).then(()=>setNotice("Provisional triage requested; veterinarian review is still required.")).catch(()=>{});
  const pendingTriage=()=>(care()??[]).flatMap(item=>item.triage).filter(item=>item.review_status==="pending");
  const openQuickAction=(action:"observation"|"care")=>{setQuickAction(current=>current===action?null:action);window.setTimeout(()=>document.getElementById(action==="observation"?"observation-input":"care-description-input")?.focus(),0)};
  const addComment=(event:SubmitEvent,eventID:string)=>{event.preventDefault();const value=commentText().trim();if(!value)return;setComments(current=>({...current,[eventID]:[...(current[eventID]??[]),value]}));setCommentText("");setCommentingOn(null)};
  const addTriageComment=async(event:SubmitEvent,catID:string,assessmentID:string)=>{event.preventDefault();const value=commentText().trim();if(!value)return;try{await command(`triage/${assessmentID}/comments`,{message:value},catID);setCommentText("");setCommentingOn(null);setNotice("Your reply was shared with the veterinarian.")}catch{}};
  const eventLabel=(type:string)=>type.startsWith("responsibility_")?"Responsibility":type==="note_recorded"?"Observation":type==="notification_recorded"?"Notification":type==="triage_requested"?"Triage":"Care update";
  const triageCommentLabel=(type:string)=>type.replace("triage_","triage ").replaceAll("_"," ");
  const allResponsibilities=()=>(care()??[]).flatMap(item=>item.responsibilities.map(responsibility=>({cat:item.cat,responsibility})));
  const allTimeline=()=>(care()??[]).flatMap(item=>{const roots=new Set(item.timeline.filter(event=>event.type==="responsibility_created").map(event=>event.responsibility_id));return item.timeline.filter(event=>(!event.type.startsWith("triage_")||event.type==="triage_requested")&&(!event.responsibility_id||event.type==="responsibility_created"||!roots.has(event.responsibility_id))).map(event=>({cat:item.cat,event}))}).sort((a,b)=>new Date(b.event.occurred_at).getTime()-new Date(a.event.occurred_at).getTime());
  const triageForNote=(catID:string,noteID:unknown)=>care()?.find(item=>item.cat.id===catID)?.triage.find(item=>item.note_ids.includes(String(noteID)));
  const triageComments=(catID:string,assessmentID:unknown)=>(care()?.find(item=>item.cat.id===catID)?.timeline??[]).filter(item=>item.type.startsWith("triage_")&&item.type!=="triage_requested"&&item.details.assessment_id===assessmentID).slice().reverse();
  const responsibilityComments=(catID:string,responsibilityID:string)=>(care()?.find(item=>item.cat.id===catID)?.timeline??[]).filter(item=>item.responsibility_id===responsibilityID&&item.type!=="responsibility_created"&&!item.type.startsWith("triage_")).slice().reverse();
  const catSelector=(label:string)=><label>{label}<select aria-label={label} value={selectedCatID()} onChange={event=>setActionCat(event.currentTarget.value)}><For each={session()?.cats}>{cat=><option value={cat.id}>{cat.profile.name}</option>}</For></select></label>;

  return <Shell>
    <section class="hero" aria-labelledby="greeting"><p class="eyebrow">Today</p><h1 id="greeting"><Show when={(session()?.cats.length??0)>1} fallback={<>How is <span>{session()?.cats[0]?.profile.name??"your cat"}</span> doing?</>}>How are <span>your cats</span> doing?</Show></h1><div class="cat-status-list"><For each={care()}>{item=><div class="status-card" data-kind={item.status.kind} aria-live="polite"><span class="status-dot" aria-hidden="true"/><div><p class="status-label">{item.cat.profile.name} · {labels[item.status.kind]??"Care status"}</p><p class="status-copy">{item.status.sentence}</p></div></div>}</For></div></section>
    <Show when={error()}><div class="error" role="alert">{error()}</div></Show><Show when={notice()}><div class="notice" role="status">{notice()}</div></Show>
    <Show when={pendingTriage().length>0}><section class="notification-area" aria-label="Notifications"><span class="notification-mark" aria-hidden="true">!</span><div><strong>{pendingTriage().length} veterinarian review{pendingTriage().length===1?" is":"s are"} pending</strong><p>You’ll see the reviewed guidance here when it is ready.</p></div></section></Show>
    <section class="quick-actions" aria-labelledby="quick-actions-title"><div><p class="eyebrow">Quick actions</p><h2 id="quick-actions-title">Add to your cats' care</h2></div><div class="quick-action-links"><button class="secondary" aria-expanded={quickAction()==="observation"} onClick={()=>openQuickAction("observation")}>Add observation</button><button class="secondary" aria-expanded={quickAction()==="care"} onClick={()=>openQuickAction("care")}>Record direct care</button><button class="secondary" aria-expanded={formVisible()} onClick={()=>setFormVisible(value=>!value)}>Add responsibility</button></div></section>
    <Show when={quickAction()}><section class="panel quick-action-form" aria-label="Quick action form"><Show when={quickAction()==="observation"}><div><p class="eyebrow">New observation</p><h2>What did you notice?</h2><form class="stack-form" onSubmit={recordNote}>{catSelector("Cat")}<label class="sr-only" for="observation-input">What did you notice?</label><textarea id="observation-input" value={noteText()} onInput={e=>setNoteText(e.currentTarget.value)} required placeholder="Eating less than usual"/><div class="form-actions"><button class="primary">Add to history</button><button class="text-button" type="button" onClick={()=>setQuickAction(null)}>Cancel</button></div></form></div></Show><Show when={quickAction()==="care"}><div><p class="eyebrow">Direct care</p><h2>What happened?</h2><form class="stack-form" onSubmit={recordCare}>{catSelector("Cat")}<label>Type<select value={careType()} onChange={e=>setCareType(e.currentTarget.value)}><option value="measurement">Measurement</option><option value="exam_performed">Exam</option><option value="medication_given">Medication given</option></select></label><label>Description<textarea id="care-description-input" value={careDescription()} onInput={e=>setCareDescription(e.currentTarget.value)} required placeholder="Weight 4.2 kg"/></label><div class="form-actions"><button class="primary">Add to history</button><button class="text-button" type="button" onClick={()=>setQuickAction(null)}>Cancel</button></div></form></div></Show></section></Show>
    <section class="workspace" aria-label="Care workspace"><article class="panel responsibilities-panel"><div class="panel-heading"><div><p class="eyebrow">Responsibilities</p><h2>What needs care</h2></div></div><Show when={formVisible()}><form class="responsibility-form" onSubmit={createResponsibility}>{catSelector("Cat")}<label>What needs to happen?<input value={title()} onInput={e=>setTitle(e.currentTarget.value)} required maxlength="160" placeholder="Annual exam"/></label><label>Category<select value={category()} onChange={e=>setCategory(e.currentTarget.value)}><option value="veterinary">Veterinary</option><option value="preventive">Preventive care</option><option value="nutrition">Nutrition</option><option value="grooming">Grooming</option><option value="other">Other</option></select></label><label>Due date <span class="optional">optional</span><input value={dueAt()} onInput={e=>setDueAt(e.currentTarget.value)} type="datetime-local"/></label><label>Repeat every <span class="optional">days</span><input value={recurrenceDays()} onInput={e=>setRecurrenceDays(Number(e.currentTarget.value))} type="number" min="0"/></label><div class="form-actions"><button class="primary" disabled={saving()}>{saving()?"Saving…":"Save responsibility"}</button><button class="text-button" type="button" onClick={()=>setFormVisible(false)}>Cancel</button></div></form></Show><div class="responsibility-list"><Show when={allResponsibilities().length>0} fallback={<p class="empty">No responsibilities yet.</p>}><For each={allResponsibilities()}>{entry=><article class={`responsibility ${entry.responsibility.state}`}><div><p class="item-cat">{entry.cat.profile.name}</p><h3>{entry.responsibility.title}</h3><p>{entry.responsibility.category} · {formatDate(entry.responsibility.due_at)} · {entry.responsibility.derived_state.replace("_"," ")}{entry.responsibility.recurrence_days?` · every ${entry.responsibility.recurrence_days} days`:""}</p></div><Show when={entry.responsibility.state==="planned"}><div class="compact-actions"><button class="complete-button" aria-label={`Mark ${entry.responsibility.title} complete`} onClick={()=>command(`responsibilities/${entry.responsibility.id}/complete`,undefined,entry.cat.id).catch(()=>{})}>Complete</button><button class="text-button" onClick={()=>deferSevenDays(entry.cat.id,entry.responsibility.id,entry.responsibility.due_at)}>Defer 7d</button><button class="text-button" onClick={()=>notify(entry.cat.id,entry.responsibility.id)}>Notify</button><button class="danger-link" onClick={()=>command(`responsibilities/${entry.responsibility.id}/cancel`,undefined,entry.cat.id).catch(()=>{})}>Cancel</button></div></Show></article>}</For></Show></div></article></section>
    <section class="history-section" aria-labelledby="history-title"><div class="section-heading"><div><p class="eyebrow">Care history</p><h2 id="history-title">Life with your cats</h2></div><p>Observations, care and responsibilities — newest first.</p></div><div class="history-feed"><Show when={allTimeline().length>0} fallback={<div class="panel empty">Care updates will appear here.</div>}><For each={allTimeline().slice(0,20)}>{entry=>{const item=entry.event;return <article class="history-card"><header><span class="feed-avatar" aria-hidden="true">{eventLabel(item.type).charAt(0)}</span><div><strong>{eventLabel(item.type)} · {entry.cat.profile.name}</strong><time dateTime={item.occurred_at}>{formatDate(item.occurred_at)}</time></div><span class="feed-kind">{item.type.replaceAll("_"," ")}</span></header><p class="feed-copy">{item.description}</p><div class="feed-actions"><button class="text-button" onClick={()=>{setCommentingOn(commentingOn()===item.id?null:item.id);setCommentText("")}}>Comment</button><Show when={item.type==="note_recorded"&&!triageForNote(entry.cat.id,item.details.note_id)}><button class="text-button" onClick={()=>requestTriage(entry.cat.id,String(item.details.note_id))}>Request triage</button></Show></div><Show when={item.type==="note_recorded"&&triageForNote(entry.cat.id,item.details.note_id)}><p class="feed-comment"><strong>Triage</strong>Triage was requested.</p></Show><Show when={item.type==="triage_requested"}><For each={triageComments(entry.cat.id,item.details.assessment_id)}>{comment=><p class="feed-comment"><strong>{comment.type==="triage_owner_commented"?String(comment.details.author_name??"Owner"):"Triage"}</strong>{comment.type==="triage_owner_commented"?comment.description:`${triageCommentLabel(comment.type)}: ${comment.description}`}</p>}</For></Show><Show when={item.type==="responsibility_created"}><For each={responsibilityComments(entry.cat.id,item.responsibility_id??"")}>{comment=><p class="feed-comment"><strong>Responsibility</strong>{comment.type.replaceAll("_"," ")}: {comment.description}</p>}</For></Show><For each={comments()[item.id]??[]}>{comment=><p class="feed-comment"><strong>You</strong>{comment}</p>}</For><Show when={commentingOn()===item.id}><form class="comment-form" onSubmit={event=>item.type==="triage_requested"?addTriageComment(event,entry.cat.id,String(item.details.assessment_id)):addComment(event,item.id)}><label class="sr-only" for={`comment-${item.id}`}>Comment on {item.description}</label><input id={`comment-${item.id}`} value={commentText()} onInput={e=>setCommentText(e.currentTarget.value)} placeholder="Write a comment…" autofocus/><button class="primary">Post</button></form></Show></article>}}</For></Show></div></section>
  </Shell>;
}
