import { For, Show, createEffect, createResource, createSignal, onMount } from "solid-js";
import { api } from "../lib/api";
import type { CareEvent, CareStatus, Cat, Note, Responsibility, TriageAssessment } from "../lib/contracts";

const labels: Record<string, string> = { clear: "All calm", planned: "Care planned", due_soon: "Coming up", overdue: "Needs attention", unknown: "Needs scheduling" };

export default function Home() {
  const [cat, { refetch: refetchCat }] = createResource(() => api<Cat>("cat"));
  const [status, { refetch: refetchStatus }] = createResource(() => api<CareStatus>("status"));
  const [responsibilities, { refetch: refetchResponsibilities }] = createResource(() => api<Responsibility[]>("responsibilities"));
  const [timeline, { refetch: refetchTimeline }] = createResource(() => api<CareEvent[]>("timeline"));
  const [notes, { refetch: refetchNotes }] = createResource(() => api<Note[]>("notes"));
  const [triage, { refetch: refetchTriage }] = createResource(() => api<TriageAssessment[]>("triage"));
  const [formVisible, setFormVisible] = createSignal(false);
  const [title, setTitle] = createSignal(""); const [category, setCategory] = createSignal("veterinary"); const [dueAt, setDueAt] = createSignal(""); const [recurrenceDays, setRecurrenceDays] = createSignal(0);
  const [noteText, setNoteText] = createSignal(""); const [careType, setCareType] = createSignal("measurement"); const [careDescription, setCareDescription] = createSignal("");
  const [profileName, setProfileName] = createSignal(""); const [birthDate, setBirthDate] = createSignal(""); const [adoptionDate, setAdoptionDate] = createSignal(""); const [photoRef, setPhotoRef] = createSignal("");
  const [error, setError] = createSignal(""); const [notice, setNotice] = createSignal(""); const [saving, setSaving] = createSignal(false); const [deleted, setDeleted] = createSignal(false);

  const [hydrated, setHydrated] = createSignal(false); onMount(() => setHydrated(true));

  createEffect(() => { const value=cat(); if(value){setProfileName(value.name);setBirthDate(value.birth_date??"");setAdoptionDate(value.adoption_date??"");setPhotoRef(value.photo_ref??"");} });
  const refresh = async () => { await Promise.all([refetchCat(),refetchStatus(),refetchResponsibilities(),refetchTimeline(),refetchNotes(),refetchTriage()]); };
  const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No due date yet";
  const command = async (path:string,body?:unknown,method="POST") => { setError("");setNotice("");try{await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});await refresh();}catch(failure){setError(failure instanceof Error?failure.message:"The care command failed");throw failure;} };

  async function createResponsibility(event:SubmitEvent){event.preventDefault();setSaving(true);try{await command("responsibilities",{title:title(),category:category(),due_at:dueAt()?new Date(dueAt()).toISOString():null,recurrence_days:recurrenceDays(),recurrence_months:0});setTitle("");setDueAt("");setRecurrenceDays(0);setFormVisible(false);setNotice("Responsibility added.");}catch{}finally{setSaving(false)}}
  async function saveProfile(event:SubmitEvent){event.preventDefault();try{await command("cat",{name:profileName(),birth_date:birthDate()||null,adoption_date:adoptionDate()||null,photo_ref:photoRef()},"PUT");setNotice("Profile saved.");}catch{}}
  async function recordNote(event:SubmitEvent){event.preventDefault();try{await command("notes",{description:noteText()});setNoteText("");setNotice("Observation recorded. It remains a note, not a diagnosis.");}catch{}}
  async function recordCare(event:SubmitEvent){event.preventDefault();try{await command("care-events",{type:careType(),description:careDescription(),responsibility_id:""});setCareDescription("");setNotice("Care event recorded.");}catch{}}
  const notify = (id:string,outcome:string) => command("notifications",{responsibility_id:id,outcome}).then(()=>setNotice(`Notification ${outcome}; responsibility state was not changed.`)).catch(()=>{});
  const deferSevenDays = (id:string,currentDue:string|null) => command(`responsibilities/${id}/defer`,{due_at:new Date(Math.max(Date.now(),currentDue?new Date(currentDue).getTime():0)+7*86400000).toISOString()}).then(()=>setNotice("Responsibility deferred by seven days.")).catch(()=>{});
  const requestTriage = (noteID:string) => command("triage",{note_ids:[noteID]}).then(()=>setNotice("Provisional triage requested; veterinarian review is still required.")).catch(()=>{});
  const reviewTriage = (id:string,decision:string,finalUrgency="") => command(`triage/${id}/review`,{veterinarian_id:"vet-local",decision,final_urgency:finalUrgency,rationale:decision==="modified"?"Prompt examination is appropriate.":"Reviewed in the local veterinarian queue."}).then(()=>setNotice("Veterinarian review recorded.")).catch(()=>{});
  async function exportData(){try{const data=await api<unknown>("export");const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="cat-care-export.json";anchor.click();URL.revokeObjectURL(url);setNotice("Owner export downloaded.");}catch(failure){setError(failure instanceof Error?failure.message:"Export failed")}}
  async function deleteData(){if(!window.confirm("Delete all local care data? This cannot be undone."))return;try{await api("data",{method:"DELETE"});setDeleted(true);setNotice("Local cat-care data deleted.");}catch(failure){setError(failure instanceof Error?failure.message:"Deletion failed")}}

  return <><header class="site-header"><a class="brand" href="/" aria-label="Cat Care home"><span aria-hidden="true">◡̈</span> Cat Care</a><span class="local-badge">Local companion</span></header><main>
    <Show when={!deleted()} fallback={<section class="deleted-state"><p class="eyebrow">Data stewardship</p><h1>Local care data deleted.</h1><p>Restart the development API to begin with a fresh in-memory environment.</p></section>}>
      <section class="hero" aria-labelledby="greeting"><p class="eyebrow">A calm view of today</p><h1 id="greeting">How is <span>{cat()?.name??"your cat"}</span> doing?</h1><div class="status-card" data-kind={status()?.kind??"loading"} aria-live="polite"><span class="status-dot" aria-hidden="true"/><div><p class="status-label">{labels[status()?.kind??""]??"Checking care status"}</p><p class="status-copy">{status()?.sentence??"Connecting to your local care record…"}</p></div></div></section>
      <Show when={error()}><div class="error" role="alert">{error()}</div></Show><Show when={notice()}><div class="notice" role="status">{notice()}</div></Show>
      <section class="workspace" aria-label="Care workspace"><article class="panel responsibilities-panel"><div class="panel-heading"><div><p class="eyebrow">Responsibilities</p><h2>What needs care</h2></div><Show when={!formVisible()}><button class="secondary" disabled={!hydrated()} onClick={()=>setFormVisible(true)}>Add responsibility</button></Show></div>
        <Show when={formVisible()}><form class="responsibility-form" onSubmit={createResponsibility}><label>What needs to happen?<input value={title()} onInput={e=>setTitle(e.currentTarget.value)} required maxlength="160" placeholder="Annual exam"/></label><label>Category<select value={category()} onChange={e=>setCategory(e.currentTarget.value)}><option value="veterinary">Veterinary</option><option value="preventive">Preventive care</option><option value="nutrition">Nutrition</option><option value="grooming">Grooming</option><option value="other">Other</option></select></label><label>Due date <span class="optional">optional</span><input value={dueAt()} onInput={e=>setDueAt(e.currentTarget.value)} type="datetime-local"/></label><label>Repeat every <span class="optional">days</span><input value={recurrenceDays()} onInput={e=>setRecurrenceDays(Number(e.currentTarget.value))} type="number" min="0"/></label><div class="form-actions"><button class="primary" disabled={saving()}>{saving()?"Saving…":"Save responsibility"}</button><button class="text-button" type="button" onClick={()=>setFormVisible(false)}>Cancel</button></div></form></Show>
        <div class="responsibility-list"><Show when={(responsibilities()?.length??0)>0} fallback={<p class="empty">No responsibilities yet.</p>}><For each={responsibilities()}>{item=><article class={`responsibility ${item.state}`}><div><h3>{item.title}</h3><p>{item.category} · {formatDate(item.due_at)} · {item.derived_state.replace("_"," ")}{item.recurrence_days?` · every ${item.recurrence_days} days`:""}</p></div><Show when={item.state==="planned"}><div class="compact-actions"><button class="complete-button" aria-label={`Mark ${item.title} complete`} onClick={()=>command(`responsibilities/${item.id}/complete`).catch(()=>{})}>Complete</button><button class="text-button" onClick={()=>deferSevenDays(item.id,item.due_at)}>Defer 7d</button><button class="text-button" onClick={()=>notify(item.id,"delivered")}>Notify</button><button class="danger-link" onClick={()=>command(`responsibilities/${item.id}/cancel`).catch(()=>{})}>Cancel</button></div></Show></article>}</For></Show></div>
      </article><aside class="panel history-panel"><div class="panel-heading"><div><p class="eyebrow">History</p><h2>Recent care</h2></div></div><ol class="timeline"><For each={(timeline()??[]).slice(0,10)}>{item=><li><strong>{item.description}</strong><span>{item.type.replaceAll("_"," ")}</span><time dateTime={item.occurred_at}>{formatDate(item.occurred_at)}</time></li>}</For></ol></aside></section>
      <section class="feature-grid"><article class="panel"><p class="eyebrow">Cat profile</p><h2>About {cat()?.name??"your cat"}</h2><form class="stack-form" onSubmit={saveProfile}><label>Name<input value={profileName()} onInput={e=>setProfileName(e.currentTarget.value)} required/></label><label>Birth date<input type="date" value={birthDate()} onInput={e=>setBirthDate(e.currentTarget.value)}/></label><label>Adoption date<input type="date" value={adoptionDate()} onInput={e=>setAdoptionDate(e.currentTarget.value)}/></label><label>Photo reference<input value={photoRef()} onInput={e=>setPhotoRef(e.currentTarget.value)} placeholder="mimi.jpg"/></label><button class="primary">Save profile</button></form></article>
        <article class="panel"><p class="eyebrow">Observations</p><h2>Notes, not diagnoses</h2><form class="stack-form" onSubmit={recordNote}><label>What did you notice?<textarea value={noteText()} onInput={e=>setNoteText(e.currentTarget.value)} required placeholder="Eating less than usual"/></label><button class="primary">Record observation</button></form><ul class="record-list"><For each={(notes()??[]).slice().reverse()}>{note=><li><span>{note.description}</span><button class="text-button" onClick={()=>requestTriage(note.id)}>Request triage</button></li>}</For></ul></article>
        <article class="panel"><p class="eyebrow">Direct care</p><h2>Record what happened</h2><form class="stack-form" onSubmit={recordCare}><label>Type<select value={careType()} onChange={e=>setCareType(e.currentTarget.value)}><option value="measurement">Measurement</option><option value="exam_performed">Exam</option><option value="medication_given">Medication given</option></select></label><label>Description<textarea value={careDescription()} onInput={e=>setCareDescription(e.currentTarget.value)} required placeholder="Weight 4.2 kg"/></label><button class="primary">Record care event</button></form></article>
        <article class="panel"><p class="eyebrow">Care triage</p><h2>Veterinarian review</h2><p class="boundary-copy">AI urgency is provisional and is not a diagnosis.</p><div class="triage-list"><Show when={(triage()?.length??0)>0} fallback={<p class="empty">No assessments waiting.</p>}><For each={(triage()??[]).slice().reverse()}>{item=><article class="triage-card"><span class={`urgency ${item.urgency}`}>{item.urgency.replace("_"," ")}</span><p>{item.rationale}</p><small>{item.uncertainty}</small><p><strong>Status:</strong> {item.review_status}{item.final_urgency?` · ${item.final_urgency}`:""}</p><Show when={item.review_status==="pending"}><div class="compact-actions"><button class="secondary" onClick={()=>reviewTriage(item.id,"accepted")}>Accept</button><button class="secondary" onClick={()=>reviewTriage(item.id,"modified","urgent")}>Mark urgent</button><button class="text-button" onClick={()=>command(`triage/${item.id}/information-requests`,{veterinarian_id:"vet-local",question:"Please share appetite and energy changes."}).catch(()=>{})}>Ask owner</button><button class="danger-link" onClick={()=>reviewTriage(item.id,"rejected")}>Reject</button></div></Show><Show when={item.review_status==="accepted"||item.review_status==="modified"}><button class="secondary" onClick={()=>command(`triage/${item.id}/follow-up`,{veterinarian_id:"vet-local",title:"Veterinarian follow-up",due_at:new Date(Date.now()+3*86400000).toISOString()}).catch(()=>{})}>Add follow-up responsibility</button></Show></article>}</For></Show></div></article>
      </section>
      <section class="panel stewardship"><div><p class="eyebrow">Data stewardship</p><h2>Your care record, under your control</h2><p>Export the complete local record or delete all owned data.</p></div><div class="compact-actions"><button class="secondary" onClick={exportData}>Download export</button><button class="danger-button" onClick={deleteData}>Delete local data</button></div></section>
    </Show>
  </main><footer>Notes and provisional triage help organize care. They are not medical diagnoses or treatment advice.</footer></>;
}
