import { A, useParams } from "@solidjs/router";
import { For, Show, createEffect, createResource, createSignal } from "solid-js";
import { Shell } from "../../components/Shell";
import { CatFace, catCoat, catCoats } from "../../components/CatFace";
import { api } from "../../lib/api";
import type { CareEvent, CareStatus, Cat, Note, Responsibility, Session, TriageAssessment } from "../../lib/contracts";

const formatDate=(value?:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(`${value}T00:00:00`)):"Unknown";

export default function CatProfile() {
  const params=useParams(); const catID=()=>params.id??"";
  const [session]=createResource(()=>api<Session>("session"));
  const [cat,{refetch:refetchCat}]=createResource(catID,id=>api<Cat>(`cat?cat_id=${encodeURIComponent(id)}`));
  const [care]=createResource(catID,async id=>{const query=`cat_id=${encodeURIComponent(id)}`;const [status,responsibilities,notes,timeline,triage]=await Promise.all([api<CareStatus>(`status?${query}`),api<Responsibility[]>(`responsibilities?${query}`),api<Note[]>(`notes?${query}`),api<CareEvent[]>(`timeline?${query}`),api<TriageAssessment[]>(`triage?${query}`)]);return {status,responsibilities:responsibilities??[],notes:notes??[],timeline:timeline??[],triage:triage??[]}});
  const [name,setName]=createSignal(""); const [birthDate,setBirthDate]=createSignal(""); const [adoptionDate,setAdoptionDate]=createSignal(""); const [photoRef,setPhotoRef]=createSignal("");
  const [error,setError]=createSignal(""); const [notice,setNotice]=createSignal("");
  createEffect(()=>{const value=cat();if(value){setName(value.name);setBirthDate(value.birth_date??"");setAdoptionDate(value.adoption_date??"");setPhotoRef(value.photo_ref??"")}});
  async function save(event:SubmitEvent){event.preventDefault();setError("");setNotice("");try{await api(`cat?cat_id=${encodeURIComponent(catID())}`,{method:"PUT",body:JSON.stringify({name:name(),birth_date:birthDate()||null,adoption_date:adoptionDate()||null,photo_ref:photoRef()})});await refetchCat();setNotice("Profile saved.")}catch(failure){setError(failure instanceof Error?failure.message:"Profile could not be saved.")}}
  const pendingTriage=()=>care()?.triage.filter(item=>item.review_status==="pending").length??0;

  return <Shell><Show when={session()?.user.mode==="owner"} fallback={<section class="panel narrow-panel"><h1>Cat profiles are managed by their owner.</h1></section>}><A class="back-link" href="/cats">← All cats</A><header class="cat-profile-header"><CatFace coat={photoRef()} size="large" label={`${cat()?.name??"Cat"} face`}/><div><p class="eyebrow">Cat profile</p><h1>About {cat()?.name??"your cat"}</h1><p>{formatDate(cat()?.birth_date)} birth · {formatDate(cat()?.adoption_date)} adoption</p></div></header><Show when={error()}><div class="error" role="alert">{error()}</div></Show><Show when={notice()}><div class="notice" role="status">{notice()}</div></Show><section class="cat-profile-layout"><article class="panel"><h2>Profile details</h2><form class="stack-form" onSubmit={save}><label>Name<input value={name()} onInput={event=>setName(event.currentTarget.value)} required/></label><label>Birth date<input type="date" value={birthDate()} onInput={event=>setBirthDate(event.currentTarget.value)}/></label><label>Adoption date<input type="date" value={adoptionDate()} onInput={event=>setAdoptionDate(event.currentTarget.value)}/></label><fieldset class="coat-picker"><legend>Closest coat</legend><p>Choose the face that looks most like your cat.</p><div><For each={catCoats}>{coat=><label class="coat-option" data-selected={catCoat(photoRef())===coat.id}><input type="radio" name="coat" value={coat.id} checked={catCoat(photoRef())===coat.id} onChange={()=>setPhotoRef(coat.id)}/><CatFace coat={coat.id} label={coat.label}/><span>{coat.label}</span></label>}</For></div></fieldset><button class="primary">Save profile</button></form></article><aside class="cat-care-summary"><section class="status-card" data-kind={care()?.status.kind??"loading"}><span class="status-dot" aria-hidden="true"/><div><p class="status-label">Care status</p><p class="status-copy">{care()?.status.sentence??"Loading care…"}</p></div></section><section class="panel"><p class="eyebrow">At a glance</p><dl class="profile-stats"><div><dt>Responsibilities</dt><dd>{care()?.responsibilities.length??0}</dd></div><div><dt>Observations</dt><dd>{care()?.notes.length??0}</dd></div><div><dt>Pending triage</dt><dd>{pendingTriage()}</dd></div></dl></section></aside></section><section class="panel cat-profile-history"><div class="section-heading"><div><p class="eyebrow">Recent care</p><h2>History for {cat()?.name??"this cat"}</h2></div></div><Show when={(care()?.timeline.length??0)>0} fallback={<p class="empty">No care history yet.</p>}><ul class="record-list"><For each={care()?.timeline.slice(0,8)}>{event=><li><span>{event.description}</span><small>{event.type.replaceAll("_"," ")}</small></li>}</For></ul></Show></section></Show></Shell>;
}
