root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o ./.air/cat-care-api ./cmd/api"
entrypoint = ["./.air/cat-care-api"]
include_ext = ["go"]
exclude_dir = [".air", "tmp", "testdata"]
exclude_regex = ["_test.go"]
delay = 300
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
